AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - EventBridge to SQS


Parameters:
  EnvironmentName:
    Type: String
    Default: test
    Description: The name of the environment to add this service to


Resources:

  # Define the SQS queue
  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties: 
      VisibilityTimeout: 360
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt:
            - "MyDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 5

  MyDeadLetterQueue: 
    Type: AWS::SQS::Queue
  
  # Define the event rule to filter for events

  EventRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: "EventRule"
      EventPattern:
        source:
          - "aws.s3"
        detail-type:
          - "Object Created"
        
        detail:
          bucket:
            name:
              - Fn::ImportValue: !Sub ${EnvironmentName}:RecordingBucketName
      Targets:
        - Arn: !GetAtt MySqsQueue.Arn
          Id: "SQSqueue"
          RetryPolicy:
            MaximumRetryAttempts: 4
            MaximumEventAgeInSeconds: 400
          
  
  # Allow EventBridge to invoke SQS
  EventBridgeToToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: SQS:SendMessage
          Resource:  !GetAtt MySqsQueue.Arn
        
        - Effect: Allow
          Principal:
            Service: ecs.amazonaws.com
          Action: SQS:ReceiveMessage
          Resource: !GetAtt MySqsQueue.Arn
      Queues:
        - Ref: MySqsQueue

Outputs:
  SQSqueueName:
    Description: SQS queue name
    Value: !GetAtt MySqsQueue.QueueName
    Export:
        Name: !Sub ${EnvironmentName}:SQSqueueName
    
  SQSqueueARN:
    Description: SQS queue ARN
    Value: !GetAtt MySqsQueue.Arn
    Export:
        Name: !Sub ${EnvironmentName}:SQSqueueARN

  SQSqueueURL:
    Description: SQS queue URL
    Value: !Ref MySqsQueue
    Export:
        Name: !Sub ${EnvironmentName}:SQSqueueURL